#!bin/bash
#creacion del grupo "escuela"
groupadd escuela
#creacion del primer usuario "profesor"
useradd -m -d  /home/profesor -s /bin/bash profesor
#creacion del segundo usuario "alumno"
useradd -m -d /home/alumno -s /bin /bash 
#agregar primer usuario
ussermod -a -G profesor escuela
#agregar segundo usuario 
ussermod -a -G alumno escuela 
#cambiar nombre del grupo "escuela" a "universidad"
groupmod -n escuela universidad 
